app_cart_order:
    path: /cart/order
    controller: App\Controller\CartController::order

app_cart_total:
    path: /cart/total
    controller: App\Controller\CartController::total


# redirecting to the cart
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /cart/order
        permanent: true